### ISSUE TITLE
Provider (MS Teams)

### ISSUE THREAD

**Issue by michaelsatish** [fluxcd/website#1057]
Hi,

The CRD example provided under the MS Teams section is missing the syntax highlighting. 

https://fluxcd.io/docs/components/notification/provider/#ms-teams
```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: msteams
  namespace: flux-system
spec:
  type: msteams
  address: <webhook-url>
  # or you can reference it from the secret with an address field
  # secretRef:
  #   name: msteam
```

With syntax highlighting
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: msteams
  namespace: flux-system
spec:
  type: msteams
  address: <webhook-url>
  # or you can reference it from the secret with an address field
  # secretRef:
  #   name: msteam

```
