### ISSUE TITLE
tmp dir error: mkdir /tmp/flux-system891620742: no space left on device

### ISSUE THREAD

**Issue by winniegakuru** [fluxcd/website#1128]
How can one be notified of the above error (tmp dir error: mkdir /tmp/flux-system891620742: no space left on device) without triggering it manually?

How to reproduce it:
```
flux reconcile kustomization tenants --with-source
I0902 13:42:52.565581  123881 request.go:665] Waited for 1.114243771s due to client-side throttling, not priority and fairness, request: GET:https://api.xxxxxxxxxxxxxxxxx?timeout=32s
► annotating GitRepository flux-system in flux-system namespace
✔ GitRepository annotated
◎ waiting for GitRepository reconciliation
✗ GitRepository reconciliation failed: 'tmp dir error: mkdir /tmp/flux-system891620742: no space left on device'
```

From the kustomize-controller no such error/warning is captured on kustomize-controller logs.

Would wish to know how best one can be notified in case disk space is full and flux can not do additional syncs

**Comment by stefanprodan** [comment]
> Would wish to know how best one can be notified in case disk space is full and flux can not do additional syncs

You can use Prometheus and Alertmanager to be notified before the disk gets filled e.g.

```
  - alert: NodeDiskRunningFull
    expr: predict_linear(node_filesystem_free[30m], 3600 * 2) < 0
    for: 10m
    labels:
      severity: critical
    annotations:
      description: device {{$labels.device}} on node {{$labels.instance}} is running
        full within the next 2 hours (mounted at {{$labels.mountpoint}})
      summary: Node disk is running full within 2 hours
```
