### ISSUE TITLE
Use separate repo for kustomization file

### ISSUE THREAD

**Issue by bibhas2** [fluxcd/website#1144]
This is regarding the **Getting Started Guide** at https://fluxcd.io/flux/get-started/.

The guide stores kustomization files directly inside the application code repo https://github.com/stefanprodan/podinfo. While this works in theory, there will be problems in real life. When application code changes are ready to go live, pull requests are approved and all changes are pushed to the main branch. This triggers a CI/CD pipeline that rebuilds a docker image and pushes it to the docker hub. However, before this step completes and the new image is available, Flux kustomize controller may detect changes in the application's Git repo and start to reconcile. In summary, the docker image may not be available at the instant Flux kustomize starts to reconcile.

I think, a best practice would be to use a separate git repo for the kustomize files. After the CI/CD pipeline has fully pushed the new docker image, it should update the image tag in the kustomization files. This should then trigger Flux reconciliation. This approach is shown in the following page.

https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/conceptual-gitops-flux2-ci-cd

Taking this approach will not introduce any additional complexity to this otherwise excellent guide.

**Comment by stefanprodan** [comment]
Updating images after they are pushed to the registry can be done with Flux Kustomizations and image automation, there is no need to split the overlays e.g.

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  images:
    - name: ghcr.io/stefanprodan/podinfo
      newName: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:podinfo:name"}
      newTag: 5.0.0 # {"$imagepolicy": "flux-system:podinfo:tag"}
```

Docs here: https://fluxcd.io/flux/guides/image-update/#configure-image-update-for-custom-resources


I consider remote bases to be an anti-pattern for Flux and I strongly recommend against them. You should be running Flux with remote bases disables, more about this here: https://fluxcd.io/flux/security/best-practices/#kustomize-controller
