### ISSUE TITLE
Add Kustomize nameReference documentation for HelmRepository sourceRef/name

### ISSUE THREAD

**Issue by kphunter** [fluxcd/website#1463]
It might help to have some additional documentation about how to teach kustomize to substitute HelmRelease names. For those who use configMap/secretGenerators, adding the following section to a `kustomizeconfig.yaml` would keep the HelmRelease and HelmRepository in sync:

```
nameReference:
- kind: HelmRepository
  fieldSpecs:
  - path: spec/chart/spec/sourceRef/name
    kind: HelmRelease
```
Seems like this may have been part of the issue here: https://github.com/fluxcd/flux2/issues/445.
