### ISSUE TITLE
Front page meeting link does not work

### ISSUE THREAD

**Issue by kingdonb** [fluxcd/website#1671]
We have this:

<img width="570" alt="Screenshot 2023-09-25 at 4 16 46 PM" src="https://github.com/fluxcd/website/assets/3286998/b06505dd-e51e-4e93-a7e7-e9549f3395b3">

but it seems to be missing a `safeURL` and the template based on hack script misunderstands that the `.where` is already a pre-formatted URL in a link.

An example from the calendar pull script I ran locally:

```yaml
...
- date: '2023-09-28'
  description: 'Join Zoom Meeting <a href="https://weaveworks.zoom.us/j/85821738864?pwd=cjk4QjRabEpUVlRlcFBqMm9UZ2xNZz09"
    target="_blank">here</a><br/> Meeting ID: 858 2173 8864 Passcode: 660308'
  label: The Flux Bug Scrub
  org_email: kingdon@weave.works
  org_name: kingdonb
  time: '17:00'
  where: <a href="https://cloud-native.slack.com/messages/flux">#flux on cncf slack</a>
...
```

I think this rendering is improved:

<img width="670" alt="Screenshot 2023-09-25 at 4 15 52 PM" src="https://github.com/fluxcd/website/assets/3286998/ced8b71b-aea2-4cd7-8199-fa30cf2b9411">

With some minor changes we could make it work as above. I'm testing those changes locally, will push a PR when I have a firm grip on them. One thing I am concerned about, if we fix this then we will have much higher visibility of the Zoom link on our front page. They're already present in the HTML code, but any scraper not smart enough to expand a hamburger via JS will miss them. Which, judging by the great infrequency with which we have Zoom bombers in Flux meetings, tells me that basically all spam robots won't scrape the links in our team calendar, because they don't click through javascript menus:

<img width="553" alt="Screenshot 2023-09-25 at 4 23 52 PM" src="https://github.com/fluxcd/website/assets/3286998/f4cd6f00-7735-43a0-94c9-680683a094ec">

I didn't want to go about fixing this accessibility issue without bringing up that I am aware, fixing this may open up a new can of worms. Zoom does not like "too public" meeting links that are unsecured. We may even find it breaks the meeting links and we have to create a new meeting after. (I have had Zoom cancel my meetings because their scraping robots found the links somewhere unsecured before.)
