### ISSUE TITLE
FQA example: How to patch CoreDNS and other pre-installed addons

### ISSUE THREAD

**Issue by qingvincentyin** [fluxcd/website#920]
Consider this section of FAQ:

- https://fluxcd.io/docs/faq/#how-to-patch-coredns-and-other-pre-installed-addons

It contains a sample yaml of how to patch an existing resource, i.e.,

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kube-dns
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: coredns
  namespace: kube-system
spec:
  replicas: 5
  selector:
    matchLabels:
      eks.amazonaws.com/component: coredns
      k8s-app: kube-dns
  template:
    metadata:
      labels:
        eks.amazonaws.com/component: coredns
        k8s-app: kube-dns
    spec:
      containers: []
```

Except for a short (but helpful) sentence explaining `.spec.containers: []`, there is no explanation of why we need all the other stuff, e.g., the entire `.spec.selector` and `.spec.template` sections.

If the only thing we intend to change is the `.spec.replicas` field (a single numeric number `5`), why do we need those other sections?

Or, am I misunderstanding the goal of the above patch?
